In [3]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import scipy
import emcee
from scipy import optimize
from scipy.stats import chi2
from scipy.stats import ks_2samp
import nestle

In [5]:
def acti_fun(x): #activation function
    return 1/(1+np.exp(-x))

def acti_deriv(x):
    return x*(1+x)

X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]]) #inputs. Columns = nodes, rows = data "point"

Y = np.array([[0],
              [1],
              [1],
              [0]]) #labels

np.random.seed(1) # make it deterministic

syn0 = 2* np.random.random((3,4)) - 1 # [-1,1[ Hvad med konstanter? Why not random.uniform?
syn1 = 2* np.random.random((4,1)) - 1 

print(X)
print(Y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


In [6]:
for i in xrange(60000):
    # feed forward  - fra X forudsig Y
    l0 = X
    l1 = acti_fun(np.dot(l0,syn0)) #np.dot for elementwise?
    l2 = acti_fun(np.dot(l1,syn1))
    
    l2_error = Y - l2
    
    l2_delta = l2_error * acti_deriv(l2) #Error * how sure are we = how much do we want to change
    
    if (i% 10000) == 0: #Print så 
        print("Error:" + str(np.mean(np.abs(l2_error))))
        
    l1_error = l2_delta.dot(syn1.T) #backpropagation
    
    l1_delta = l1_error *acti_deriv(l1)
    
    #Update weights
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

NameError: name 'xrange' is not defined